<?php

namespace AppBundle\Repository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCountries($id)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c.id')
            ->addSelect('c.countryCode,c.sentAndroid,c.sentIos, c.clickAndroid, c.clickIos')
            ->where('c.notification = :id')
            ->setParameter('id', $id)
        ;
        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
