<?php

namespace AppBundle\Repository;

/**
 * NotificationConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
